[package]
name = "cloud-storage-sync"
version = "0.0.1"
authors = ["Andrey Kuznetsov <fear@loathing.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cloud-storage = "0.3.7"
snafu = { version = "0.6.6", features = ["backtraces"] }
mime_guess = "2.0.3"
mime = "0.3.16"
reqwest = "0.10.4"
log = "0.4.8"
crc32c = "0.4"
base64 = "0.12"
arrayref = "0.3.6"

[dev-dependencies]
env_logger = "0.7.1"
tempdir = "0.3"
dotenv = "0.15.0"
