name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        toolchain: nightly
    - run: 'echo "$SERVICE_ACCOUNT_CONTENT" > service-account.json'
      shell: bash
      env:
        SERVICE_ACCOUNT_CONTENT: ${{secrets.SERVICE_ACCOUNT_CONTENT}}
    - name: Run cargo test
      uses: actions-rs/cargo@v1
      env:
        SERVICE_ACCOUNT: service-account.json
        BUCKET: ${{secrets.BUCKET}}
      with:
        command: test
        toolchain: nightly

          
